HIVES = [
    {"id": 66651, "name": "Beute 1"},
    {"id": 66652, "name": "Beute 2"},
    {"id": 66653, "name": "Beute 3"},
    {"id": 66654, "name": "Beute 4"},
    {"id": 66699, "name": "Beute 5"},
    {"id": 66700, "name": "Beute 6"},
]
DEVICES = [
    {"id": 5835, "name": "Hive Heart 1", "hive_id": 66651, "type": "heart"},
    {"id": 5905, "name": "Hive Heart 2", "hive_id": 66652, "type": "heart"},
    {"id": 5906, "name": "Hive Heart 3", "hive_id": 66653, "type": "heart"},
    {"id": 5907, "name": "Hive Heart 4", "hive_id": 66654, "type": "heart"},
    {"id": 5908, "name": "Hive Heart 5", "hive_id": 66699, "type": "heart"},
    {"id": 5909, "name": "Hive Heart 6", "hive_id": 66700, "type": "heart"},
    {"id": 3187, "name": "Scientific Scale 1", "hive_id": 66654, "type": "scale"},
    {"id": 5834, "name": "Scientific Scale 2", "hive_id": 66699, "type": "scale"},
]
SENSORS_HEART = [
    {
        "name": "bv",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 6,
        "output_measurement_id": 6,
        "input_abbr": "bv",
        "output_abbr": "bv",
    },
    {
        "name": "h_i",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 47,
        "output_measurement_id": 47,
        "input_abbr": "h_i",
        "output_abbr": "h_i",
    },
    {
        "name": "rssi",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 22,
        "output_measurement_id": 22,
        "input_abbr": "rssi",
        "output_abbr": "rssi",
    },
    {
        "name": "s_bin098_146Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 26,
        "output_measurement_id": 26,
        "input_abbr": "s_bin098_146Hz",
        "output_abbr": "s_bin098_146Hz",
    },
    {
        "name": "s_bin146_195Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 27,
        "output_measurement_id": 27,
        "input_abbr": "s_bin146_195Hz",
        "output_abbr": "s_bin146_195Hz",
    },
    {
        "name": "s_bin195_244Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 28,
        "output_measurement_id": 28,
        "input_abbr": "s_bin195_244Hz",
        "output_abbr": "s_bin195_244Hz",
    },
    {
        "name": "s_bin244_293Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 29,
        "output_measurement_id": 29,
        "input_abbr": "s_bin244_293Hz",
        "output_abbr": "s_bin244_293Hz",
    },
    {
        "name": "s_bin293_342Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 30,
        "output_measurement_id": 30,
        "input_abbr": "s_bin293_342Hz",
        "output_abbr": "s_bin293_342Hz",
    },
    {
        "name": "s_bin342_391Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 31,
        "output_measurement_id": 31,
        "input_abbr": "s_bin342_391Hz",
        "output_abbr": "s_bin342_391Hz",
    },
    {
        "name": "s_bin391_439Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 32,
        "output_measurement_id": 32,
        "input_abbr": "s_bin391_439Hz",
        "output_abbr": "s_bin391_439Hz",
    },
    {
        "name": "s_bin439_488Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 33,
        "output_measurement_id": 33,
        "input_abbr": "s_bin439_488Hz",
        "output_abbr": "s_bin439_488Hz",
    },
    {
        "name": "s_bin488_537Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 34,
        "output_measurement_id": 34,
        "input_abbr": "s_bin488_537Hz",
        "output_abbr": "s_bin488_537Hz",
    },
    {
        "name": "s_bin537_586Hz",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 35,
        "output_measurement_id": 35,
        "input_abbr": "s_bin537_586Hz",
        "output_abbr": "s_bin537_586Hz",
    },
    {
        "name": "t",
        "inside": True,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 17,
        "output_measurement_id": 17,
        "input_abbr": "t_i",
        "output_abbr": "t_i",
    },
]
SENSORS_SCALE = [
    {
        "name": "w_v",
        "inside": False,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 7,
        "output_measurement_id": 7,
        "input_abbr": "w_v",
        "output_abbr": "w_v",
    },
    {
        "name": "t",
        "inside": False,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 1,
        "output_measurement_id": 1,
        "input_abbr": "t",
        "output_abbr": "t",
    },
    {
        "name": "h",
        "inside": False,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 2,
        "output_measurement_id": 2,
        "input_abbr": "h",
        "output_abbr": "h",
    },
    {
        "name": "bv",
        "inside": False,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 6,
        "output_measurement_id": 6,
        "input_abbr": "bv",
        "output_abbr": "bv",
    },
    {
        "name": "rssi",
        "inside": False,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 22,
        "output_measurement_id": 22,
        "input_abbr": "rssi",
        "output_abbr": "rssi",
    },
    {
        "name": "p",
        "inside": False,
        "offset": 0,
        "multiplier": 1,
        "input_measurement_id": 3,
        "output_measurement_id": 3,
        "input_abbr": "p",
        "output_abbr": "p",
    },
]
