"""Schema update

Revision ID: 8791c1f72cbf
Revises: e93f5aabde99
Create Date: 2025-07-26 21:54:40.475846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8791c1f72cbf'
down_revision: Union[str, Sequence[str], None] = 'e93f5aabde99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('fftPeak', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('history', sa.Column('fft', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'fft')
    op.drop_column('history', 'fftPeak')
    # ### end Alembic commands ###
